"""Editable personality/character trait pool.

Add, remove, or reorder traits here. The app samples one trait per persona.
This starter list is intentionally broad; paste the larger 200-item list here
when you want to restore the full vocabulary.
"""


TRAITS = [
    "Speculative Designer",
    "Design Fiction Researcher",
    "Hollow Knight Speedrunner",
    "Pixel Artist",
    "Unity Game Dev",
    "Interactive Fiction Writer",
    "Graphic Novelist",
    "Data Scientist",
    "UX Researcher",
    "PhD Researcher",
    "Rock Climber",
    "Wild Water Swimmer",
    "Pottery Hobbyist",
    "Digital Artist",
    "Board Game Fanatic",
    "Vinyl Collector",
    "Experimental Musician",
    "Plant Parent",
    "Coffee Snob",
    "Urban Explorer",
    "Slow Living Proponent",
    "Indie Game Dev",
    "Podcast Host",
    "Street Photographer",
    "Solarpunk Advocate",
    "Accessibility Designer",
    "Inclusive Design Researcher",
    "Creative Coder",
    "New Media Artist",
    "Narrative Designer",
    "TTRPG Game Master",
    "Zine Maker",
    "Small-batch Coffee Roaster",
    "Fermentation Scientist",
    "Future Studies Researcher",
    "Field Recording Artist",
    "Urban Geographer",
    "Cargo Bike Advocate",
    "Service Designer",
    "Interaction Designer",
        "Adventurous", "Sarcastic", "Empathetic", "Ambitious", "Introverted", "Speculative Designer", "Design Fiction Researcher", "PhD Researcher", "Hollow Knight Speedrunner", "Pixel Artist",
        "Polyamory Advocate", "Lactose Intolerant Foodie", "Unity Game Dev", "Tabletop RPG Master", "Graphic Novelist", "Anime Curator", "Ethical Non-Monogamy Educator", "Interactive Fiction Writer", "Stoic", "Whimsical",
        "Deeply Neurotic", "Cynical", "Hopeless Romantic", "Pragmatic", "Golden Retriever Energy", "Meticulous", "Spontaneous", "Reserved", "Assertive", "Charismatic",
        "Highly Sensitive", "Meditation Enthusiast", "Competitive", "Software Engineer", "Barista", "ER Nurse", "Graphic Designer", "Civil Servant", "Tattoo Artist", "Librarian",
        "Yoga Instructor", "Data Scientist", "Freelance Writer", "Carpentry Apprentice", "Corporate Lawyer", "Kindergarten Teacher", "Social Media Manager", "Chef de Partie", "Architect", "Dog Walker",
        "Electrician", "Investment Banker", "Flight Attendant", "Floral Designer", "Music Producer", "Biotech Lab Tech", "UX Researcher", "History Buff", "Philosophy Dropout", "Art History Major",
        "MBA Student", "Self-Taught Coder", "Theoretical Physics Nerd", "Linguistics Student", "Film School Grad", "Law School Survivor", "Medical Student", "Rock Climber", "Marathon Runner", "Muay Thai Practitioner",
        "Wild Water Swimmer", "Cyclist", "Powerlifter", "Skateboarder", "Surfer", "Hiker", "Yoga Devotee", "Tennis Player", "Archer", "Fencer",
        "Pilates Enthusiast", "Kayaker", "Pottery Hobbyist", "Knitter", "Digital Artist", "Cosplayer", "Vinyl Collector", "Board Game Fanatic", "Speedrunner", "TTRPG Game Master",
        "Woodworker", "Oil Painter", "Street Photographer", "Experimental Musician", "Journaling Addict", "Calligrapher", "Plant Parent", "Antique Hunter", "Bread Baker", "Urban Explorer",
        "Astrology Skeptic", "True Crime Junkie", "Bird Watcher", "Coffee Snob", "Tea Sommelier", "Zero-Waste Advocate", "Minimalist", "Maximalist", "Concert Goer", "Slow Living Proponent",
        "Film Photographer", "Anxious Overachiever", "Amateur Astronomer", "Mixologist", "Comic Book Colorist", "Beekeeping Hobbyist", "Aquarium Landscaper", "Micro-influencer", "Ghost Hunter", "Stand-up Comedian",
        "Perfume Collector", "Historical Reenactor", "Model Train Builder", "Indie Game Dev", "Podcast Host", "Thrift Store Flipper", "Interior Design Blogger", "Guerilla Gardener", "Sourdough Expert", "Amateur Mycologist",
        "Homebrewer", "Vintage Car Restorer", "Puppeteer", "Voice Actor", "Translator", "Public Speaker", "Activist", "Volunteer Firefighter", "Scuba Diver", "Paraglider",
        "Chess Grandmaster", "Geocacher", "Parkour Traceur", "Sneakerhead", "Watch Collector", "Zine Maker", "Screenwriter", "Ballroom Dancer", "Burlesque Performer", "Drag King",
        "Experimental Cook", "Fermentation Fanatic", "Sailing Enthusiast", "Mountain Biker", "Caving Explorer", "Lockpicking Hobbyist", "Origami Artist", "Bonsai Tree Caretaker", "Stained Glass Maker", "Leatherworker",
        "Blacksmith", "Soap Maker", "Candle Maker", "Jewelry Designer", "Upholsterer", "Renewable Energy Advocate", "Urban Planner", "Wildlife Photographer", "Documentary Filmmaker", "Poet",
        "Potluck Host", "Trivia Night Champion", "Karaoke Star", "Escape Room Expert", "Puzzle Solver", "Magic Trick Performer", "Juggler", "Unicyclist", "Slackliner", "Poi Spinner",
        "Stargazer", "Meteorology Nerd", "Oceanography Student", "Entomology Collector", "Paleontology Fan", "Bilingual", "Polyglot", "Sign Language Learner", "Braille Reader", "Cryptocurrency Skeptic",
        "Venture Capitalist", "Ethical Hacker", "Cybersecurity Expert", "Robotics Hobbyist", "Drone Pilot", "3D Printing Nerd", "Laser Cutting Artist", "Retro Console Restorer", "Arcade Game Collector", "Mechanical Keyboard Enthusiast",
        "Audiophile", "Synthesizer Geek", "Jazz Trumpeter", "Classical Cellist", "Punk Bassist", "Opera Singer", "Spoken Word Artist", "Manga Illustrator", "Light Novel Writer", "Anime Curator",
        "Tea Ceremony Practitioner", "Calligraphy Master", "Kintsugi Artist", "Origami Specialist", "Taekwondo Black Belt", "Capoeira Practitioner", "Fencing Coach", "Equestrian", "Falconer", "Dog Trainer",
        "Cat Foster Parent", "Urban Beekeeper", "Permaculture Designer", "Tiny House Builder", "Off-grid Liver", "Busker", "Street Performer", "Circus Artist", "Contortionist", "Fire Breather",
        "Clown", "Mime", "Living Statue", "Ventriloquist", "Magician", "Historian", "Genealogist", "Archaeologist", "Anthropologist", "Sociologist",
        "Psychologist", "Counselor", "Social Worker", "Humanitarian", "Philanthropist", "Taxidermist", "Meteorologist", "Park Ranger", "Cartographer", "Clockmaker",
        "Butcher", "Baker", "Candlestick Maker", "Shipwright", "Cooper", "Wheelwright", "Milliner", "Haberdasher", "Cobbler", "Blacksmith",
        "Goldsmith", "Silversmith", "Lapidary", "Enameller", "Glassblower", "Potter", "Weaver", "Spinner", "Dyer", "Fuller",
        "Quilter", "Embroiderer", "Lacemaker", "Crocheter", "Tatting Artist", "Rug Hooker", "Basket Weaver", "Broom Maker", "Cooper", "Tanner",
        "Farrier", "Saddler", "Ostler", "Gamekeeper", "Poacher-turned-keeper", "Woodsman", "Charcoal Burner", "Hedgelayer", "Dry Stone Waller", "Thatcher",
        "Plasterer", "Mason", "Carpenter", "Joiner", "Turner", "Carver", "Gilder", "Painter", "Decorator", "Glazier",
        "Plumber", "Electrician", "Mechanic", "Engineer", "Technician", "Scientist", "Researcher", "Professor", "Teacher", "Lecturer",
        "Tutor", "Instructor", "Coach", "Trainer", "Mentor", "Consultant", "Advisor", "Specialist", "Expert", "Analyst",
        "Manager", "Director", "Executive", "Officer", "Administrator", "Coordinator", "Superintendent", "Supervisor", "Foreman", "Overseer",
        "Clerk", "Secretary", "Assistant", "Receptionist", "Telephonist", "Typist", "Bookkeeper", "Accountant", "Auditor", "Cashier",
        "Salesperson", "Agent", "Broker", "Dealer", "Merchant", "Trader", "Vendor", "Hawker", "Peddler", "Costermonger",
        "Chef", "Cook", "Baker", "Confectioner", "Pastry Chef", "Saucier", "Sommelier", "Waiter", "Waitress", "Host",
        "Bartender", "Barista", "Kitchen Porter", "Dishwasher", "Cleaner", "Janitor", "Caretaker", "Housekeeper", "Nanny", "Au Pair",
        "Nurse", "Doctor", "Surgeon", "Dentist", "Optician", "Pharmacist", "Vet", "Paramedic", "Midwife", "Physiotherapist",
        "Psychotherapist", "Counselor", "Social Worker", "Carer", "Volunteer", "Activist", "Politician", "Diplomat", "Civil Servant", "Judge",
        "Lawyer", "Solicitor", "Barrister", "Paralegal", "Police Officer", "Detective", "Soldier", "Sailor", "Airman", "Firefighter",
        "Pilot", "Driver", "Chauffeur", "Conductor", "Guard", "Porter", "Courier", "Postman", "Messenger", "Delivery Driver",
        "Farmer", "Gardener", "Fisherman", "Forester", "Miner", "Quarryman", "Oil Rigger", "Construction Worker", "Laborer", "Stevedore",
        "Artist", "Musician", "Actor", "Dancer", "Singer", "Writer", "Poet", "Playwright", "Novelist", "Journalist",
        "Editor", "Publisher", "Photographer", "Filmmaker", "Designer", "Illustrator", "Animator", "Architect", "Surveyor", "Engineer",
        "Programmer", "Developer", "Analyst", "Scientist", "Mathematician", "Statistician", "Economist", "Historian", "Geographer", "Sociologist",
        "Psychologist", "Anthropologist", "Archaeologist", "Linguist", "Philosopher", "Theologian", "Priest", "Minister", "Rabbi", "Imam",
        "Monk", "Nun", "Missionary", "Evangelist", "Prophet", "Guru", "Shaman", "Mystic", "Astrologer", "Psychic",
        "Medium", "Healer", "Witch", "Wizard", "Sorcerer", "Magician", "Alchemist", "Necromancer", "Diviner", "Augur",
        "Hero", "Villain", "Anti-hero", "Sidekick", "Mentor", "Guardian", "Herald", "Shapeshifter", "Trickster", "Shadow",
        "Warrior", "Knight", "Paladin", "Ranger", "Rogue", "Thief", "Assassin", "Bard", "Druid", "Cleric",
        "Mage", "Warlock", "Sorcerer", "Enchanter", "Necromancer", "Summoner", "Illusionist", "Alchemist", "Artificer", "Monk",
        "King", "Queen", "Prince", "Princess", "Duke", "Duchess", "Count", "Countess", "Baron", "Baroness",
        "Lord", "Lady", "Knight", "Squire", "Page", "Peasant", "Serf", "Slave", "Freeman", "Citizen",
        "Rebel", "Revolutionary", "Traitor", "Spy", "Informer", "Agent", "Saboteur", "Assassin", "Mercenary", "Soldier",
        "General", "Admiral", "Captain", "Lieutenant", "Sergeant", "Corporal", "Private", "Recruit", "Veteran", "Deserter",
        "Refugee", "Exile", "Outcast", "Hermit", "Wanderer", "Nomad", "Pilgrim", "Traveler", "Explorer", "Adventurer",
        "Merchant", "Banker", "Usurer", "Tax Collector", "Customs Officer", "Smuggler", "Pirate", "Corsair", "Privateer", "Brigand",
        "Bandit", "Outlaw", "Highwayman", "Thief", "Pickpocket", "Burglar", "Forger", "Counterfeiter", "Con Artist", "Swindler",
        "Gambler", "Prostitute", "Pimp", "Beggar", "Pauper", "Orphan", "Widow", "Widower", "Cripple", "Leper",
        "Saint", "Martyr", "Confessor", "Doctor of the Church", "Pope", "Cardinal", "Bishop", "Abbot", "Prior", "Curate",
        "Vicar", "Rector", "Deacon", "Acolyte", "Sacristan", "Beadle", "Verger", "Sexton", "Choirmaster", "Organist",
        "Bellringer", "Gravedigger", "Executioner", "Torturer", "Jailer", "Watchman", "Constable", "Sheriff", "Bailiff", "Beadle",
        "Mayor", "Alderman", "Councilor", "Burgess", "Freeman", "Guildmaster", "Apprentice", "Journeyman", "Master", "Grandmaster",
        "Scribe", "Illuminator", "Calligrapher", "Cartographer", "Chroncler", "Annalist", "Archivist", "Librarian", "Curator", "Antiquary",
        "Collector", "Connoisseur", "Critic", "Reviewer", "Commentator", "Reporter", "Correspondent", "Broadcaster", "Presenter", "Anchor",
        "Blogger", "Vlogger", "Influencer", "Streamer", "Gamer", "Cosplayer", "Otaku", "Trekkie", "Whovian", "Fan",
        "Aficionado", "Enthusiast", "Devotee", "Follower", "Disciple", "Acolyte", "Zealot", "Fanatic", "Believer", "Skeptic",
        "Cynic", "Pessimist", "Optimist", "Idealist", "Realist", "Pragmatist", "Opportunist", "Stoic", "Epicurean", "Hedonist",
        "Ascetic", "Puritan", "Libertine", "Philistine", "Intellectual", "Egghead", "Nerd", "Geek", "Dork", "Bohemian",
        "Hippie", "Punk", "Goth", "Emo", "Prep", "Jock", "Hipster", "Yuppie", "Chav", "Townie",
        "Redneck", "Hillbilly", "Yokel", "Bumpkin", "Rustic", "Peasant", "Proletarian", "Bourgeois", "Aristocrat", "Noble",
        "Royal", "Imperial", "Divine", "Mortal", "Human", "Alien", "Cyborg", "Robot", "Android", "AI",
        "Ghost", "Vampire", "Werewolf", "Zombie", "Demon", "Angel", "God", "Goddess", "Titan", "Giant",
        "Dwarf", "Elf", "Halfling", "Gnome", "Troll", "Orc", "Goblin", "Dragon", "Phoenix", "Unicorn",
        "Mermaid", "Centaur", "Satyr", "Faun", "Dryad", "Nymph", "Siren", "Harpy", "Sphinx", "Chimera",
        "Hydra", "Kraken", "Leviathan", "Behemoth", "Manticore", "Griffon", "Basilisk", "Wyvern", "Drake", "Salamander",
        "Sylph", "Undine", "Gnome", "Salamander", "Efreet", "Djinn", "Genie", "Ghouls", "Wight", "Wraith",
        "Specter", "Apparition", "Poltergeist", "Banshee", "Valkyrie", "Amazon", "Ninja", "Samurai", "Ronin", "Monk",
        "Shaolin", "Yakuza", "Triad", "Mafioso", "Gangster", "Mobster", "Hoodlum", "Thug", "Ruffian", "Bully",
        "Tyrant", "Dictator", "Despot", "Autocrat", "Monarch", "Emperor", "Czar", "Sultan", "Shah", "Khan",
        "Caliph", "Pharaoh", "Chief", "Patriarch", "Matriarch", "Elder", "Leader", "Head", "Chief", "Commander",
        "Captain", "Master", "Owner", "Boss", "Employer", "Manager", "Director", "President", "Chairman", "Governor",
        "Premier", "Chancellor", "Minister", "Secretary", "Commissioner", "Ambassador", "Envoy", "Consul", "Delegate", "Representative",
        "Senator", "Congressman", "MP", "Councilor", "Mayor", "Reeve", "Warden", "Sheriff", "Constable", "Marshal",
        "Inspector", "Sergeant", "Corporal", "Private", "Trooper", "Cadet", "Midshipman", "Ensign", "Lieutenant", "Commander",
        "Captain", "Commodore", "Admiral", "General", "Marshal", "Veteran", "Retired", "Pensioner", "Elderly", "Aged",
        "Middle-aged", "Young Adult", "Teenager", "Child", "Infant", "Baby", "Newborn", "Twin", "Triplet", "Sibling",
        "Parent", "Mother", "Father", "Grandparent", "Grandmother", "Grandfather", "Aunt", "Uncle", "Cousin", "Nephew",
        "Niece", "Spouse", "Husband", "Wife", "Partner", "Lover", "Friend", "Best Friend", "Buddy", "Pal",
        "Chum", "Mate", "Colleague", "Associate", "Partner", "Ally", "Enemy", "Rival", "Foe", "Nemesis",
        "Stranger", "Neighbor", "Acquaintance", "Contact", "Connection", "Client", "Customer", "Patient", "Student", "Pupil",
        "Disciple", "Apprentice", "Trainee", "Intern", "Novice", "Beginner", "Amateur", "Professional", "Expert", "Master",
        "Veteran", "Survivor", "Winner", "Loser", "Champion", "Hero", "Villain", "Legend", "Icon", "Idol",
        "Star", "Celebrity", "Socialite", "Influencer", "Public Figure", "Citizen", "Resident", "Native", "Foreigner", "Immigrant",
        "Expatriate", "Refugee", "Tourist", "Visitor", "Guest", "Host", "Owner", "Tenant", "Landlord", "Lodger",
        "Boarder", "Squatter", "Homeless", "Drifter", "Vagrant", "Tramp", "Hobo", "Wanderer", "Nomad", "Gypsy",
        "Traveler", "Pilgrim", "Adventurer", "Explorer", "Pioneer", "Settler", "Colonist", "Founder", "Creator", "Inventor",
        "Discoverer", "Innovator", "Visionary", "Dreamer", "Thinker", "Scholar", "Intellectual", "Philosopher", "Sage", "Genius",
        "Polymath", "Expert", "Specialist", "Authority", "Leader", "Pioneer", "Pathfinder", "Trailblazer", "Groundbreaker", "Revolutionary",
        "Rebel", "Dissident", "Protester", "Activist", "Advocate", "Supporter", "Promoter", "Champion", "Defender", "Protector",
        "Guardian", "Keeper", "Steward", "Curator", "Caretaker", "Warden", "Janitor", "Porter", "Doorman", "Concierge",
        "Butler", "Valet", "Maid", "Housekeeper", "Cook", "Chef", "Waiter", "Server", "Bartender", "Barista",
        "Driver", "Chauffeur", "Pilot", "Captain", "Engineer", "Mechanic", "Technician", "Operator", "User", "Consumer",
        "Producer", "Maker", "Builder", "Creator", "Designer", "Artist", "Writer", "Author", "Poet", "Painter",
        "Sculptor", "Musician", "Composer", "Singer", "Dancer", "Actor", "Performer", "Entertainer", "Comedian", "Magician",
        "Athlete", "Player", "Competitor", "Contestant", "Challenger", "Opponent", "Rival", "Partner", "Teammate", "Coach",
        "Trainer", "Manager", "Referee", "Umpire", "Judge", "Juror", "Witness", "Lawyer", "Attorney", "Solicitor",
        "Barrister", "Advocate", "Counsel", "Prosecutor", "Defendant", "Plaintiff", "Litigant", "Criminal", "Offender", "Felon",
        "Convict", "Prisoner", "Inmate", "Jailbird", "Outlaw", "Fugitive", "Deserter", "Traitor", "Spy", "Agent",
        "Soldier", "Warrior", "Fighter", "Mercenary", "Knight", "Samurai", "Ninja", "Assassin", "Executioner", "Killer",
        "Murderer", "Victim", "Survivor", "Witness", "Bystander", "Passerby", "Observer", "Spectator", "Audience", "Fan",
        "Follower", "Disciple", "Acolyte", "Adherent", "Devotee", "Believer", "Skeptic", "Critic", "Reviewer", "Editor",
        "Publisher", "Journalist", "Reporter", "Anchor", "Host", "Presenter", "Broadcaster", "Commentator", "Analyst", "Expert",
        "Specialist", "Consultant", "Advisor", "Mentor", "Tutor", "Teacher", "Professor", "Scholar", "Student", "Researcher",
        "Scientist", "Engineer", "Technician", "Doctor", "Nurse", "Pharmacist", "Vet", "Dentist", "Optician", "Psychologist",
        "Social Worker", "Counselor", "Therapist", "Physio", "Midwife", "Paramedic", "Firefighter", "Police Officer", "Soldier", "Sailor", "Acoustic Ecologist", "Urban Forager", "Hyper-local Journalist", "Scent Historian", "Experimental Glaciologist", "Doughnut Artist", "Neon Sign Restorer", "Typewriter Collector", "Brutalist Architecture Fan", "Analog Synth Enthusiast",
        "Bread Sommelier", "Moss Gardener", "Fermentation Scientist", "Solarpunk Advocate", "Liminal Space Photographer", "Vexillologist", "Obscure Map Collector", "Bio-mimicry Designer", "Human-Robot Interaction Student", "Wearable Tech Maker",
        "Upcycled Fashion Designer", "Sustainable Travel Blogger", "Minimalist Backpacker", "Off-grid Living Consultant", "Tiny House Enthusiast", "Van Life Nomad", "Modernist Furniture Scout", "Retro Toy Collector", "Pinball Mechanic", "Arcade Cabinet Artist",
        "Street Food Critic", "Small-batch Coffee Roaster", "Artisanal Cheesemaker", "Wild Yeast Specialist", "Kitchen Alchemist", "Culinary Anthropologist", "Food Systems Researcher", "Regenerative Farmer", "Urban Orchardist", "Beekeeping Mentor",
        "Entomologist for Fun", "Lepidopterist", "Amateur Herpetologist", "Bird Call Mimic", "Nature Sound Recordist", "Deep Sea Explorer (Simulated)", "Marine Conservationist", "Coral Reef Restorationist", "Sea Glass Artist", "Driftwood Sculptor",
        "Landscape Architect", "Permaculture Teacher", "Rainwater Harvesting Expert", "Guerrilla Composter", "Fungi Cultivator", "Truffle Hunter (Amateur)", "Forest Bather", "Tree Climber", "Survivalist Skills Instructor", "Primitive Technology Fan",
        "Ethnobotanist", "Herbal Medicine Student", "Traditional Dyer", "Handweaver", "Natural Pigment Maker", "Stone Carver", "Dry Stone Waller", "Hedge Layer", "Traditional Thatcher", "Straw Bale Builder",
        "Cob House Enthusiast", "Earthship Dweller", "Adobe Architect", "Rammed Earth Builder", "Sustainable Materials Researcher", "Circular Economy Consultant", "Waste-to-Art Sculptor", "Zero-Waste Shop Owner", "Eco-anxiety Counselor", "Climate Fiction Writer",
        "Future Studies Researcher", "Speculative Biologist", "Xenolinguistics Fan", "Astro-biologist (Aspiring)", "Space Lawyer", "Lunar Geologist", "Satellite Tracker", "Dark Sky Advocate", "Light Pollution Researcher", "Telescope Builder",
        "Planetarium Narrator", "Science Communicator", "Math Rock Guitarist", "Ambient Drone Producer", "Modular Synth Patching Nerd", "Field Recording Artist", " Foley Artist", "Experimental Sound Designer", "Voice Over Artist", "Audiobook Narrator",
        "Podcast Editor", "ASMR Creator", "Radio Playwright", "Community Radio DJ", "Vinyl Pressing Plant worker", "Turntablist", "Scratch DJ", "Electronic Music Historian", "Club Culture Researcher", "Nightlife Sociologist",
        "Urban Geographer", "Transit Enthusiast", "Bicycle Mechanic", "Cargo Bike Advocate", "Infrastructure Nerd", "Civil Engineering Student", "Smart City Planner", "Accessibility Designer", "Inclusive Design Researcher", "Universal Design Advocate",
        "Tactile Graphic Designer", "Braille Literacy Advocate", "Disability Rights Activist", "Neurodiversity Advocate", "Autistic Self-Advocacy Leader", "Sensory Room Designer", "Adaptive Sports Coach", "Wheelchair Basketball Player", "Blind Runner", "Guide Dog Trainer",
        "Service Animal Advocate", "Animal Behaviorist", "Canine Cognition Researcher", "Feline Ethologist", "Equine Therapist", "Wildlife Rehabilitator", "Raptor Handler", "Falconry Apprentice", "Owl Conservator", "Bat Protector",
        "Invasive Species Specialist", "Native Plant Advocate", "Wildflower Photographer", "Botanical Illustrator", "Plant Pathologist", "Soil Microbiologist", "Compost Tea Brewer", "Vertical Farm Operator", "Hydroponic Hobbyist", "Aquaponic System Builder",
        "Indoor Jungle Specialist", "Succulent Propagator", "Rare Aroid Collector", "Bonsai Aesthetics Student", "Ikebana Practitioner", "Kokedama Maker", "Terrarium Landscaper", "Paludarium Builder", "Bio-active Enclosure Designer", "Vivarium Hobbyist",
        "Aquarium Chemist", "Planted Tank Enthusiast", "Shrimp Breeder", "Rare Cichlid Keeper", "Goldfish Specialist", "Koi Pond Designer", "Water Feature Builder", "Solar Pump Innovator", "Renewable Energy Consultant", "Wind Turbine Tech",
        "Geothermal Engineer", "Hydroelectric Researcher", "Battery Storage Specialist", "Electric Vehicle Conversionist", "E-bike Builder", "Solar Car Designer", "Sustainable Aviation Student", "Green Shipping Advocate", "Hydrogen Fuel Cell Researcher", "Nuclear Fusion Optimist",
        "Plasma Physicist", "Quantum Computing Student", "Cryogenic Engineer", "Superconductivity Researcher", "Materials Scientist", "Nanotechnology Hobbyist", "Graphene Researcher", "Carbon Fiber Fabricator", "Composite Materials Expert", "Resin Artist",
        "Fluid Art Practitioner", "Encaustic Painter", "Egg Tempera Specialist", "Fresco Restorer", "Iconographer", "Gold Leaf Gilder", "Sign Painter", "Pinstriper", "Airbrush Artist", "Stencil Graffiti Artist",
        "Wheatpaste Artist", "Guerilla Knitter", "Yarn Bomber", "Needlefelter", "Punch Needle Artist", "Rug Tufter", "Macrame Specialist", "Basketry Teacher", "Willow Weaver", "Rush Seating Restorer",
        "Cane Chair Repairer", "Upholstery Student", "Antique Fabric Collector", "Vintage Pattern Cutter", "Costume Historian", "Theatrical Milliner", "Shoe Maker (Bespoke)", "Leather Carver", "Saddlery Enthusiast", "Whip Maker",
        "Bookbinder", "Paper Maker (Handmade)", "Marbling Artist", "Letterpress Printer", "Linocut Printmaker", "Woodcut Artist", "Etching Enthusiast", "Lithography Student", "Risograph Artist", "Zine Librarian",
        "Self-Publishing Consultant", "Indie Bookstore Owner", "Rare Book Scout", "First Edition Collector", "Literary Translator", "Comparative Literature Scholar", "Poetry Slam Organizer", "Spoken Word Poet", "Experimental Novelist", "Flash Fiction Writer",
        "Screenwriter (Unproduced)", "Playwright", "Dramaturg", "Theatre Director", "Stage Manager", "Lighting Designer", "Projection Mapper", "VFX Artist", "Motion Graphics Designer", "Title Sequence Designer",
        "Film Essayist", "Cinephile", "Video Store Clerk (Ex)", "Film Archivist", "Celluloid Restorer", "Projectionist", "Independent Cinema Owner", "Film Festival Programmer", "Documentary Subject", "Cinematographer",
        "Steadicam Operator", "Drone Cinematographer", "Underwater Photographer", "Macro Photographer", "Astrophotographer", "Infrared Photographer", "Cyanotype Artist", "Daguerreotype Revitalist", "Wet Plate Collodion Photographer", "Polaroid Enthusiast",
        "Toy Camera Photographer", "Street Portraitist", "Documentary Photographer", "Conflict Journalist", "Photojournalist", "Fashion Photographer", "Food Photographer", "Interior Photographer", "Architectural Photographer", "Real Estate Photographer",
        "Product Photographer", "Commercial Director", "Creative Director", "Art Director", "Brand Strategist", "Copywriter", "Content Strategist", "UX Writer", "Information Architect", "Service Designer",
        "Interaction Designer", "Visual Designer", "UI Developer", "Front-end Engineer", "Back-end Engineer", "Full-stack Developer", "Mobile App Dev", "Game Engine Programmer", "Physics Programmer", "AI Engineer",
        "Machine Learning Researcher", "Data Engineer", "Cloud Architect", "DevOps Engineer", "Site Reliability Engineer", "Cybersecurity Analyst", "Penetration Tester", "Digital Forensics Expert", "OSINT Researcher", "Privacy Advocate",
        "Blockchain Developer", "Smart Contract Auditor", "DAO Contributor", "NFT Artist", "Generative Artist", "Creative Coder", "New Media Artist", "Digital Preservationist", "Net Art Historian", "Glitch Artist",
        "Machinima Filmmaker", "Virtual World Architect", "VR Developer", "AR Experience Designer", "Metaverse Researcher", "Avatar Designer", "V-tuber", "Stream Overlay Designer", "Esports Analyst", "Speedrun Commentator",
        "Level Designer", "Quest Designer", "Narrative Designer", "Technical Artist", "Environment Artist", "Character Modeler", "Rigging Artist", "3D Animator", "Texture Artist", "Lighting Artist",
        "Sound Designer", "Game Composer", "QA Tester", "Game Producer", "Community Manager", "Localization Specialist", "Player Support Lead", "Gaming Historian", "Retro Gaming Collector", "Arcade Preservationist",
        "Board Game Designer", "Tabletop RPG Writer", "Dice Maker", "Miniature Painter", "Wargaming Tactician", "LARP Organizer", "Escape Room Designer", "Puzzle Maker", "Crossword Constructor", "Sudoku Expert",
        "Chess Player", "Go Player", "Bridge Player", "Poker Semi-pro", "Cardist", "Magician", "Mentalist", "Hypnotist", "Sideshow Performer", "Sword Swallower",
        "Fire Spinner", "Flow Arts Teacher", "Juggler", "Unicyclist", "Tightrope Walker", "Slackliner", "Aerialist", "Trapeze Artist", "Contortionist", "Handbalancer",
        "Acrobat", "Parkour Athlete", "Freerunner", "Tricker", "Capoeirista", "Martial Artist", "Historical European Martial Arts", "Kendo Practitioner", "Fencer", "Archer",
        "Olympic Weightlifter", "Powerlifter", "Bodybuilder", "CrossFit Enthusiast", "Yoga Teacher", "Pilates Instructor", "Spin Instructor", "Barre Teacher", "Zumba Dancer", "Salsa Dancer",
        "Swing Dancer", "Tango Dancer", "Ballroom Dancer", "Contemporary Dancer", "Ballet Dancer", "Hip Hop Dancer", "Breakdancer", "Choreographer", "Dance Movement Therapist", "Physical Therapist",
        "Sports Masseur", "Osteopath", "Chiropractor", "Nutritionist", "Dietitian", "Personal Trainer", "Health Coach", "Life Coach", "Executive Coach", "Leadership Consultant",
        "Public Speaker", "Storyteller", "Toastmaster", "Debater", "Philosophy Teacher", "Ethics Professor", "Theologian", "Biblical Scholar", "Islamic Studies Scholar", "Buddhist Monk (Ex)",
        "Meditation Guide", "Mindfulness Teacher", "Breathwork Facilitator", "Reiki Practitioner", "Acupuncturist", "Ayurvedic Consultant", "Yoga Therapist", "Sound Healer", "Crystal Shop Owner", "Tarot Reader",
        "Astrologer", "Numerologist", "Palm Reader", "Graphologist", "Paranormal Investigator", "Cryptozoologist", "UFO Researcher", "Conspiracy Theory Analyst", "Cult Researcher", "True Crime Blogger",
        "Private Investigator", "Bodyguard", "Bouncer", "Security Consultant", "Intelligence Analyst", "Strategic Forecaster", "Crisis Negotiator", "Mediator", "Conflict Resolution Expert", "Human Rights Lawyer",
        "Environmental Lawyer", "Animal Rights Lawyer", "Entertainment Lawyer", "IP Attorney", "Patent Agent", "Notary Public", "Justice of the Peace", "Wedding Officiant", "Funeral Director", "End-of-life Doula",
        "Grief Counselor", "Art Therapist", "Music Therapist", "Drama Therapist", "Occupational Therapist", "Speech Pathologist", "Special Education Teacher", "ESL Teacher", "Adult Literacy Tutor", "Museum Educator",
        "Gallery Docent", "Art Registrar", "Archivist", "Digital Librarian", "Special Collections Librarian", "Children's Librarian", "School Librarian", "Genealogist", "Family Historian", "Oral Historian",
        "Archaeologist", "Bioarchaeologist", "Zooarchaeologist", "Underwater Archaeologist", "Cultural Resource Manager", "Heritage Consultant", "Museum Director", "Curator", "Exhibition Designer", "Collections Manager",
        "Art Conservator", "Paintings Restorer", "Sculpture Conservator", "Paper Conservator", "Textile Conservator", "Object Conservator", "Science Museum Tech", "Planetarium Operator", "Zookeeper", "Aquarist",
        "Animal Caretaker", "Vet Tech", "Groomer", "Dog Daycare Owner", "Pet Sitter", "Cat Cafe Owner", "Exotic Animal Specialist", "Equine Manager", "Barn Manager", "Stable Hand",
        "Farrier", "Blacksmith", "Knifemaker", "Bladesmith", "Gunsmith", "Locksmith", "Safe Cracker (Legal)", "Security Tech", "Home Automation Expert", "Audio Visual Installer",
        "Piano Tuner", "Luthier", "Violin Maker", "Guitar Tech", "Drum Tech", "Instrument Restorer", "Antique Clock Repairer", "Watchmaker", "Jeweler", "Diamond Setter",
        "Gemologist", "Lapidary Artist", "Enameller", "Silversmith", "Goldbeater", "Caster", "Mold Maker", "Industrial Designer", "Ergonomist", "Human Factors Engineer",
        "Aeronautical Engineer", "Aerospace Technician", "Satellite Engineer", "Robotics Engineer", "Automation Specialist", "Mechatronics Tech", "Electronics Hobbyist", "Ham Radio Operator", "Shortwave Listener", "Scanner Nerd",
        "Telecommunications Tech", "Fiber Optic Splicer", "Network Admin", "SysAdmin", "Database Admin", "Webmaster", "Blogger", "Micro-blogger", "Vlogger", "Influencer",
        "Brand Ambassador", "Affiliate Marketer", "SEO Specialist", "SEM Manager", "Email Marketer", "Growth Hacker", "Digital Nomad", "Remote Worker", "Co-working Space Manager", "Incubator Director",
        "Venture Capital Analyst", "Angel Investor", "Stock Trader", "Options Trader", "Forex Trader", "Crypto Trader", "Financial Planner", "Tax Preparer", "Enrolled Agent", "Forensic Accountant",
        "Actuary", "Risk Manager", "Insurance Broker", "Underwriter", "Claims Adjuster", "Real Estate Agent", "Property Manager", "Appraiser", "Home Inspector", "Mortgage Broker",
        "Title Agent", "Leasing Consultant", "Hotel Manager", "Concierge", "Front Desk Clerk", "Bellhop", "Housekeeper", "Executive Housekeeper", "Butler", "Estate Manager",
        "Personal Assistant", "Virtual Assistant", "Event Planner", "Wedding Planner", "Party Planner", "Corporate Event Manager", "Conference Organizer", "Trade Show Coordinator", "Caterer", "Private Chef",
        "Personal Chef", "Pastry Chef", "Chocolatier", "Baker", "Bread Baker", "Cake Decorator", "Food Stylist", "Recipe Developer", "Test Kitchen Manager", "Wine Critic",
        "Beer Judge", "Cicerone", "Sommelier", "Mixologist", "Bar Manager", "Barista", "Coffee Quality Grader", "Tea Taster", "Whiskey Connoisseur", "Sake Expert",
        "Restaurant Manager", "Maître d'", "Server", "Busser", "Dishwasher", "Prep Cook", "Line Cook", "Sous Chef", "Executive Chef", "Restaurateur",
        "Food Truck Owner", "Street Vendor", "Market Vendor", "Farmer's Market Manager", "Co-op Manager", "Grocery Store Manager", "Retail Manager", "Visual Merchandiser", "Personal Shopper", "Stylist",
        "Fashion Designer", "Textile Designer", "Pattern Maker", "Tailor", "Dressmaker", "Milliner", "Jewelry Designer", "Accessory Designer", "Shoe Designer", "Bag Designer",
        "Makeup Artist", "Hair Stylist", "Barber", "Esthetician", "Nail Technician", "Spa Manager", "Massage Therapist", "Reflexologist", "Aromatherapist", "Herbalist",
        "Naturopath", "Homeopath", "Chiropractor", "Osteopath", "Acupuncturist", "Physiotherapist", "Occupational Therapist", "Speech Therapist", "Psychologist", "Psychiatrist",
        "Social Worker", "Counselor", "Therapist", "Life Coach", "Spiritual Director", "Priest", "Minister", "Rabbi", "Imam", "Monk",
        "Nun", "Missionary", "Chaplain", "Theologian", "Biblical Scholar", "Religious Educator", "Youth Minister", "Church Organist", "Choir Director", "Cantor",
        "Judge", "Magistrate", "Lawyer", "Attorney", "Solicitor", "Barrister", "Paralegal", "Legal Secretary", "Court Reporter", "Bailiff",
        "Police Officer", "Detective", "Sheriff", "Deputy", "State Trooper", "Federal Agent", "Customs Officer", "Border Patrol Agent", "Prison Guard", "Probation Officer",
        "Firefighter", "EMT", "Paramedic", "Flight Nurse", "Search and Rescue Tech", "Coast Guard Member", "Soldier", "Sailor", "Airman", "Marine",
        "Officer", "NCO", "Warrant Officer", "Veteran", "Military Historian", "Defense Analyst", "Intelligence Officer", "Diplomat", "Foreign Service Officer", "Ambassador",
        "Politician", "Senator", "Representative", "Governor", "Mayor", "City Councilor", "School Board Member", "Political Strategist", "Campaign Manager", "Lobbyist",
        "Activist", "Community Organizer", "Non-profit Director", "Grant Writer", "Fundraiser", "Volunteer Coordinator", "Philanthropist", "Humanitarian Worker", "Peace Corps Volunteer", "UN Worker",
        "Economist", "Sociologist", "Psychologist", "Anthropologist", "Historian", "Geographer", "Political Scientist", "Linguist", "Archaeologist", "Paleontologist",
        "Astronomer", "Physicist", "Chemist", "Biologist", "Geologist", "Meteorologist", "Oceanographer", "Environmental Scientist", "Geneticist", "Neuroscientist",
        "Doctor", "Surgeon", "Nurse", "Physician Assistant", "Dentist", "Pharmacist", "Vet", "Optometrist", "Podiatrist", "Radiologist",
        "Engineer", "Architect", "Surveyor", "Urban Planner", "Software Developer", "Data Scientist", "Statistician", "Mathematician", "Actuary", "Accountant",
        "Pilot", "Captain", "Truck Driver", "Train Engineer", "Bus Driver", "Taxi Driver", "Courier", "Postman", "Librarian", "Teacher",
        "Professor", "Artist", "Musician", "Writer", "Actor", "Dancer", "Photographer", "Filmmaker", "Designer", "Chef"
]
